### ISSUE TITLE
Enable Dependabot Version Updates

### ISSUE THREAD

**Issue by JamieBort** [JamieBort/Portfolio-Website#17]
See screenshot from https://github.com/JamieBort/Portfolio-Website/settings/security_analysis
<img width="798" alt="Screen Shot 2024-02-26 at 21 01 28" src="https://github.com/JamieBort/Portfolio-Website/assets/4405730/b4f53947-515a-4995-962d-ea600fa94624">

Possibly have this as my yml file:
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "monthly"

```
